// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGsziuxg4lxb3JXEEmVIdkW-A8TGKXwUQ',
    appId: '1:952476844716:web:73ff578625a68466219509',
    messagingSenderId: '952476844716',
    projectId: 'auth-d2ddc',
    authDomain: 'auth-d2ddc.firebaseapp.com',
    storageBucket: 'auth-d2ddc.appspot.com',
    measurementId: 'G-57JLMVNJSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQAJYzoEtcoyJ64XMfDAEQ-ZOjsIbRw7g',
    appId: '1:952476844716:android:a9d8f908dcc1e45d219509',
    messagingSenderId: '952476844716',
    projectId: 'auth-d2ddc',
    storageBucket: 'auth-d2ddc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfCe3tmEuWN4-k1DVZ5PrnyIf_pbLSrh4',
    appId: '1:952476844716:ios:dece651d8df3ab9c219509',
    messagingSenderId: '952476844716',
    projectId: 'auth-d2ddc',
    storageBucket: 'auth-d2ddc.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfCe3tmEuWN4-k1DVZ5PrnyIf_pbLSrh4',
    appId: '1:952476844716:ios:92a067a8cd90786d219509',
    messagingSenderId: '952476844716',
    projectId: 'auth-d2ddc',
    storageBucket: 'auth-d2ddc.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase.RunnerTests',
  );
}
